<?php

namespace admin\personneBundle\Repository;

/**
 * rdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rdvRepository extends \Doctrine\ORM\EntityRepository
{
}
